version: '2.3'

services:
  statping:
    container_name: statping
    image: adamboutcher/statping-ng:latest
    restart: always
    volumes:
      - statping_data:/app
    environment:
      DB_CONN: sqlite
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.statping.entrypoints=websecure"
      - "traefik.http.routers.statping.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.services.statping.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  statping_data: