version: '3'

networks:
    proxy:
      external: true

services:

  tirith-api:
    container_name: tirith-api
    image: "ghcr.io/toobeeh/tirith/tirith-api:latest"
    restart: always
    environment:
      - DB_DOMAIN_NAME=mariadb
      - DISCORD_OAUTH_CLIENT_ID=${DISCORD_OAUTH_CLIENT_ID}
      - DISCORD_OAUTH_CLIENT_SECRET=${DISCORD_OAUTH_CLIENT_SECRET}
      - DISCORD_OAUTH_REDIRECT=${DISCORD_OAUTH_REDIRECT}
      - DISCORD_API_TOKEN=${DISCORD_API_TOKEN}
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tirith-api.entrypoints=websecure"
      - "traefik.http.routers.tirith-api.rule=Host(`${TIRITH_API_DOMAIN_NAME}`)"
      - "traefik.http.services.tirith-api.loadbalancer.server.port=3000"