version: "3.0"

services:
  typo-agent:
    container_name: typo-agent
    image: "ghcr.io/toobeeh/typo-agent-scraper/typo-agent-scraper-image:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.typo-agent.entrypoints=websecure"
      - "traefik.http.routers.typo-agent.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.services.typo-agent.loadbalancer.server.port=3000"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true