version: '3'

volumes:
  typo-mariadb:
    driver: local

networks:
    proxy:
      external: true

services:
  mariadb:
    container_name: mariadb
    image: typo-mariadb
    build:
      context: ./mariadb
      args:
        DB_ADMIN_USERNAME: ${DB_ADMIN_USERNAME}
        DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
     - typo-mariadb:/var/lib/mysql
    networks:
      - proxy
    ports:
     - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - UPLOAD_LIMIT=500M
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.rule=Host(`${PMA_DOMAIN_NAME}`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

  tirith-api:
    container_name: tirith-api
    image: "ghcr.io/toobeeh/tirith/tirith-api:latest"
    restart: always
    environment:
      - DB_DOMAIN_NAME=mariadb
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tirith-api.entrypoints=websecure"
      - "traefik.http.routers.tirith-api.rule=Host(`${TIRITH_API_DOMAIN_NAME}`)"
      - "traefik.http.services.tirith-api.loadbalancer.server.port=3000"

  tirith-frontend:
    container_name: tirith-frontend
    image: "ghcr.io/toobeeh/tirith/tirith-frontend:latest"
    restart: always
    environment:
      - API_DOMAIN_NAME=${TIRITH_API_DOMAIN_NAME}
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tirith-frontend.entrypoints=websecure"
      - "traefik.http.routers.tirith-frontend.rule=Host(`${TIRITH_FRONTEND_DOMAIN_NAME}`)"
      - "traefik.http.services.tirith-frontend.loadbalancer.server.port=80"

  ithil-rebirth:
    container_name: ithil-rebirth
    image: "ghcr.io/toobeeh/ithil-rebirth/ithil-rebirth:latest"
    restart: always
    environment:
      - DB_DOMAIN_NAME=mariadb
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.ithil-smain.entrypoints=websecure"
      - "traefik.http.routers.ithil-smain.rule=Host(`${ITHIL_SMAIN_DOMAIN_NAME}`)"
      - "traefik.http.services.ithil-smain.loadbalancer.server.port=4000"

      - "traefik.http.routers.ithil-sdrop.entrypoints=websecure"
      - "traefik.http.routers.ithil-sdrop.rule=Host(`${ITHIL_SDROP_DOMAIN_NAME}`)"
      - "traefik.http.services.ithil-sdrop.loadbalancer.server.port=4001"

      - "traefik.http.routers.ithil-sworker1.entrypoints=websecure"
      - "traefik.http.routers.ithil-sworker1.rule=Host(`${ITHIL_SWORKER1_DOMAIN_NAME}`)"
      - "traefik.http.services.ithil-sworker1.loadbalancer.server.port=4002"

      - "traefik.http.routers.ithil-sworker2.entrypoints=websecure"
      - "traefik.http.routers.ithil-sworker2.rule=Host(`${ITHIL_SWORKER2_DOMAIN_NAME}`)"
      - "traefik.http.services.ithil-sworker2.loadbalancer.server.port=4003"

      - "traefik.http.routers.ithil-sworker3.entrypoints=websecure"
      - "traefik.http.routers.ithil-sworker3.rule=Host(`${ITHIL_SWORKER3_DOMAIN_NAME}`)"
      - "traefik.http.services.ithil-sworker3.loadbalancer.server.port=4004"

      - "traefik.http.routers.ithil-sworker4.entrypoints=websecure"
      - "traefik.http.routers.ithil-sworker4.rule=Host(`${ITHIL_SWORKER4_DOMAIN_NAME}`)"
      - "traefik.http.services.ithil-sworker4.loadbalancer.server.port=4005"

      - "traefik.http.routers.ithil-sworker5.entrypoints=websecure"
      - "traefik.http.routers.ithil-sworker5.rule=Host(`${ITHIL_SWORKER5_DOMAIN_NAME}`)"
      - "traefik.http.services.ithil-sworker5.loadbalancer.server.port=4006"

      - "traefik.http.routers.ithil-sworker6.entrypoints=websecure"
      - "traefik.http.routers.ithil-sworker6.rule=Host(`${ITHIL_SWORKER6_DOMAIN_NAME}`)"
      - "traefik.http.services.ithil-sworker6.loadbalancer.server.port=4007"

      - "traefik.http.routers.ithil-sworker7.entrypoints=websecure"
      - "traefik.http.routers.ithil-sworker7.rule=Host(`${ITHIL_SWORKER7_DOMAIN_NAME}`)"
      - "traefik.http.services.ithil-sworker7.loadbalancer.server.port=4008"

      - "traefik.http.routers.ithil-sworker8.entrypoints=websecure"
      - "traefik.http.routers.ithil-sworker8.rule=Host(`${ITHIL_SWORKER8_DOMAIN_NAME}`)"
      - "traefik.http.services.ithil-sworker8.loadbalancer.server.port=4009"

      - "traefik.http.routers.ithil-sworker9.entrypoints=websecure"
      - "traefik.http.routers.ithil-sworker9.rule=Host(`${ITHIL_SWORKER9_DOMAIN_NAME}`)"
      - "traefik.http.services.ithil-sworker9.loadbalancer.server.port=4010"