version: "3"

networks:
    proxy:
      external: true
      
services:
  yacht:
    container_name: yacht
    restart: unless-stopped
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    image: selfhostedpro/yacht
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.yacht.entrypoints=websecure"
      - "traefik.http.routers.yacht.rule=Host(`${YACHT_DOMAIN_NAME}`)"
      - "traefik.http.services.yacht.loadbalancer.server.port=8000"

volumes:
  yacht: