version: "3.0"

networks:
    proxy:
      external: true

services:
  palantir-core:
    container_name: palantir-core
    image: "ghcr.io/toobeeh/palantir-rebirth/palantir-core:latest"
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - GRPC_URL=${GRPC_URL}
      - DISCORD_TOKEN=${DISCORD_CORE_TOKEN}
      - PATREON_TOKEN=${PATREON_TOKEN}
