version: '3'

networks:
    proxy:
      external: true

services:

  valmar:
    cpus: 2
    container_name: valmar
    image: "ghcr.io/toobeeh/valmar:latest"
    restart: always
    environment:
      - DB_DOMAIN_NAME=mariadb
    networks:
      - proxy